### ISSUE TITLE
Add support for multiple file inputs?

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#62] opened 2017-03-09 15:18 UTC
$SUBJECT

**Comment by tnozicka** [comment] 2017-03-10 18:49
Yes, it is planned :) Now we can track it in an issue.
https://github.com/redhat-developer/opencompose/blob/master/pkg/cmd/convert.go#L84

**Comment by surajssd** [comment] 2017-03-13 10:46
will this be just adding services from multiple files and converting it, or will this also be a merge of objects like `kompose` does?

**Comment by tnozicka** [comment] 2017-03-13 11:25
we had some notion of merging objects but no decision has been made yet. we will discuss it once the more pressing issues are addressed

**Comment by tnozicka** [comment] 2017-03-13 15:49
actually, a duplicate of https://github.com/redhat-developer/opencompose/issues/47

**Closed as completed by tnozicka** 2017-03-13 15:49 UTC
Labels: duplicate
